---
- name: Converge
  hosts: all
  roles:
    - role: lean_delivery.java
      transport: web
      transport_web: "{{ lookup('env','STORAGE_AWS') }}/oracle-java/jdk-8u202-windows-x64.exe"
      java_major_version: 8
      java_minor_version: 202
      java_package: jdk
      java_tarball_install: False
    - role: lean_delivery.solr_standalone
    - role: ansible-role-solr-hybris-config
      transport: "web"
      transport_web: "{{ lookup('env','STORAGE_EPC') }}/hybris-solr"
  vars:
    solr_change_default_password: False
