---
- name: Converge
  hosts: all
  roles:
    - role: lean_delivery.java
      java_major_version: 8
      java_package: jdk
      java_tarball_install: False
    - role: lean_delivery.solr_standalone
    - role: ansible-role-solr-hybris-config
      transport: web
      transport_web: '{{ lookup("env","STORAGE_AWS") }}/hybris-solr'
  vars:
    solr_change_default_password: False
    solr_auth_configure: False
