---
- name: 'Fetch solr patch with {{ solr_patch_transport }} transport'
  include_tasks: '{{ transport_driver }}'
  with_first_found:
    - '../fetch/{{ solr_patch_transport }}.yml'
    - '../fetch/unknown-transport.yml'
  loop_control:
    loop_var: transport_driver

- name: Install solr patch hybris components
  unarchive:
    src: '{{ patch_conf_file.patch_src }}'
    dest: '{{ patch_conf_file.patch_dest }}'
    owner: '{{ solr_user }}'
    group: '{{ solr_group }}'
    mode: 0755
    creates: '{{ patch_conf_file.patch_creates }}'
    remote_src: True
  loop:
    - patch_src: '{{ solr_contrib_hybris_patch }}'
      patch_dest: '{{ solr_dest_path }}'
      patch_creates: '{{ solr_dest_path }}/contrib/hybris'
    - patch_src: '{{ solr_data_hybris_patch }}'
      patch_dest: '{{ solr_home }}'
      patch_creates: '{{ solr_home }}/configsets/default'
    loop_control:
      loop_var: patch_conf_file
  become: True
  notify:
    - restart Solr Linux

- name: Start service
  service:
    name: '{{ solr_service_name }}'
    state: started
    enabled: True
  become: True
  when:
    - solr_service_start
