---
- name: Install contrib hybris components
  unarchive:
    src: '{{ solr_contrib_hybris_patch }}'
    dest: '{{ solr_dest_path }}'
    owner: '{{ solr_user }}'
    group: '{{ solr_group }}'
    mode: 0755
    creates: '{{ solr_dest_path }}/contrib/hybris'
    remote_src: True
  become: True
  notify:
    - restart solr linux

- name: Install data hybris components
  unarchive:
    src: '{{ solr_data_hybris_patch }}'
    dest: '{{ solr_home }}'
    owner: '{{ solr_user }}'
    group: '{{ solr_group }}'
    mode: 0755
    creates: '{{ solr_home }}/configsets/default'
    remote_src: True
  become: True
  notify:
    - restart solr linux

- name: Force all notified handlers
  meta: flush_handlers
