---
- name: 'Fetch solr patch with {{ solr_patch_transport }} transport'
  include_tasks: '{{ transport_driver }}'
  with_first_found:
    - '../win_fetch/{{ solr_patch_transport }}.yml'
    - '../fetch/unknown-transport.yml'
  loop_control:
    loop_var: transport_driver

- name: Copy contrib and data hybris components
  win_copy:
    src: '{{ hybris_patch_file }}'
    dest: '{{ solr_dest_main_path }}/'
    force: True
    remote_src: True
  loop:
    - '{{ solr_contrib_hybris_patch }}'
    - '{{ solr_data_hybris_patch }}'
  loop_control:
    loop_var: hybris_patch_file

- name: Install data hybris components
  win_unzip:
    src: '{{ solr_data_hybris_patch }}'
    dest: '{{ solr_dest_path }}/server/'
    creates: '{{ solr_dest_path }}/contrib/hybris/solr'
  notify: restart Solr Windows

- name: Install contrib hybris components
  win_unzip:
    src: '{{ solr_contrib_hybris_patch }}'
    dest: '{{ solr_dest_path }}'
    creates: '{{ solr_dest_path }}/contrib/hybris'
  notify: restart Solr Windows

- name: start Solr Windows
  win_service:
    name: '{{ solr_service_name }}'
    state: started
  when:
    - solr_service_start
