---
- name: 'Fetch solr patch with {{ transport }} transport'
  include_tasks: '{{ transport_driver }}'
  with_first_found:
    - '../win_fetch/{{ transport }}.yml'
    - '../fetch/unknown-transport.yml'
  loop_control:
    loop_var: transport_driver

- name: Upload contrib hybris components
  win_copy:
    src: '{{ solr_contrib_hybris_patch }}'
    dest: '{{ solr_dest_main_path }}/'
    force: True
    remote_src: True

- name: Upload data hybris components
  win_copy:
    src: '{{ solr_data_hybris_patch }}'
    dest: '{{ solr_dest_main_path }}/'
    force: True
    remote_src: True

- name: Install contrib hybris components
  win_unzip:
    src: '{{ solr_dest_main_path }}/{{ solr_contrib_hybris_patch }}'
    dest: '{{ solr_dest_path }}'
    creates: '{{ solr_dest_path }}/contrib/hybris'
  notify: restart solr windows

- name: Install data hybris components
  win_unzip:
    src: '{{ solr_dest_main_path }}/{{ solr_data_hybris_patch }}'
    dest: '{{ solr_dest_path }}/server/'
    creates: '{{ solr_dest_path }}/contrib/hybris/solr'
  notify: restart solr windows

- name: Force all notified handlers
  meta: flush_handlers
