---
- name: Download contrib artifact from web
  get_url:
    url: '{{ solr_patch_transport_web }}/{{ solr_contrib_hybris_patch_name }}'
    dest: '{{ download_path }}/{{ solr_contrib_hybris_patch_name }}'
  register: contrib_file_downloaded
  until: contrib_file_downloaded is succeeded
  retries: 3
  delay: 2

- name: Download data artifact from web
  get_url:
    url: '{{ solr_patch_transport_web }}/{{ solr_data_hybris_patch_name }}'
    dest: '{{ download_path }}/{{ solr_data_hybris_patch_name }}'
  register: data_file_downloaded
  until: data_file_downloaded is succeeded
  retries: 3
  delay: 2

- name: Downloaded artifact
  set_fact:
    solr_hybris_patch_contrib: '{{ contrib_file_downloaded.dest }}'
    solr_hybris_patch_data: '{{ data_file_downloaded.dest }}'
