---
- name: Converge
  hosts: all
  roles:
    - role: lean_delivery.java
      transport: web
      transport_web: "{{ lookup('env','STORAGE_AWS') }}/oracle-java/jdk-8u211-linux-x64.tar.gz"
      java_major_version: 8
      java_minor_version: 211
      java_package: jdk
      java_tarball_install: True
    - role: lean_delivery.solr_standalone
    - role: ansible-role-solr-hybris-config
      transport: web
      transport_web: '{{ lookup("env","STORAGE_AWS") }}/hybris-solr'
  vars:
    solr_version: 7.5.0
    solr_change_default_password: False
    solr_auth_configure: False
