---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: delegated
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-epc-centos7-solr-hybris-config
    image: CentOS7_64-bit
    shape: small
    region: EPAM-BY2
    wait_timeout: 3600
    groups:
      - rhel_family
  - name: test-epc-ubuntu1804-solr-hybris-config
    image: Ubuntu18.04_64-bit
    shape: small
    region: EPAM-BY2
    wait_timeout: 3600
    groups:
      - debian_family
provisioner:
  name: ansible
  log: True
  inventory:
    group_vars:
      all:
        solr_version: 7.5.0
  playbooks:
    create: ../resources/provisioning/EPC/create.yml
    prepare: ../resources/prepare.yml
    destroy: ../resources/provisioning/EPC/destroy.yml
  config_options:
    ssh_connection:
      control_path: "/var/ans/%%h"
  lint:
    name: ansible-lint
  env:
    ANSIBLE_LIBRARY: ${ANSIBLE_LIBRARY}
scenario:
  name: cloud-epc-delegated
verifier:
  name: testinfra
  options:
    verbose: true
  directory: ../resources/tests/
  lint:
    name: flake8
