---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-solr-hybris-config
      solr_patch_transport: web
      solr_patch_transport_web: '{{ lookup("env","STORAGE_EPC") }}/hybris-solr'
  vars:
    solr_version: 7.5.0
