---
- name: Converge
  hosts: all
  roles:
    - role: lean_delivery.java
    - role: lean_delivery.solr_standalone
    - role: ansible-role-solr-hybris-config
      transport: web
      transport_web: '{{ lookup("env","STORAGE_EPC") }}/hybris-solr'
  vars:
    solr_version: 7.5.0
    solr_change_default_password: False
    solr_auth_configure: False
    solr_use_java_version_8: False
