---
- name: Converge
  hosts: all
  roles:
    - role: lean_delivery.java
    - role: lean_delivery.solr_standalone
    - role: ansible-role-solr-hybris-config
      transport: "web"
      transport_web: "{{ lookup('env','STORAGE_AWS') }}/hybris-solr"
  vars:
    change_default_password: False
